### ISSUE TITLE
リノート解除を実装して欲しい

### ISSUE THREAD

**Issue by sevenc-nanashi** [poppingmoon/aria#116]
### Summary

タイトル通りです。自分が発見できてないだけの可能性もありますが…

### Purpose

誤RNをなくせる

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by poppingmoon** [comment]
#115 で修正済みです

**Comment by sevenc-nanashi** [comment]
すごいタイムリーで草
ありがとうございます！

**Comment by poppingmoon** [comment]
直ってなかった
