### ISSUE TITLE
タブ一覧に「その他」が欲しい

### ISSUE THREAD

**Issue by sevenc-nanashi** [poppingmoon/aria#123]
### Summary

タブ一覧に、毎回タイムラインを選択する「その他」的なボタンがあると便利だと思います。

### Purpose

- 一度しか見ない時（例：めったに見ないアンテナ、ioのLTL）に便利

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by poppingmoon** [comment]
あまりメリットがわかりません
たまにしか見ない場合は、アンテナであればメニューのもっと！からアンテナを選べばタイムラインをみることができますし、他のサーバーのLTLはユーザー名の下のサーバー名をタップして右上のメニューから開くことができます
また見に来るつもりならタブに追加して端のほうに置いておけばいいような気がします

実装としても変則的なものになりそうなのでやりたくありません

**Comment by sevenc-nanashi** [comment]
あ、サーバーのところから見れたんですね（知らなかった）
ありがとうございます
