### ISSUE TITLE
他アプリの共有ボタンからノートすると自分のノートが削除不能になり、また自分のアカウントのアイコン、名前、IDがTL以外で表示されなくなる。

### ISSUE THREAD

**Issue by natumi-kaoru** [poppingmoon/aria#151]
### 💡 Summary

ニュースサイトなど他のアプリの共有ボタンからAriaを選択してノートを投稿する（以後、これによって投稿したノートを「共有ノート」と書きます。）と、任意の自分の投稿したノートについて「…」ボタンで表示されるメニューから「削除」、「削除して編集」ボタンが表示されず、選ぶことができなくなっています。
![Screenshot_20240512-235331](https://github.com/poppingmoon/aria/assets/145369415/e3a07d96-c318-4f9d-b0e6-62b86220c773)

また、共有ノートを投稿したアカウントのアイコンがサイドメニューで表示されなくなったり、投稿画面でアイコンとアカウント名、IDが表示されなくなったりします。ただし、投稿は通常通り行えます。
![Screenshot_20240512-235713](https://github.com/poppingmoon/aria/assets/145369415/d7a72fef-aee7-4f16-93be-20bdfddce9bb)
![Screenshot_20240512-235835](https://github.com/poppingmoon/aria/assets/145369415/7e1c2432-87ff-496b-b6b8-e28da327e026)

これらの事象は一度アプリを終了するまで続きます。

### 🥰 Expected Behavior

共有ノート投稿後、アプリを再起動せずとも：
- 通常通りノートの削除を行える。
- アイコン、アカウント名、IDの表示が維持される。

### 🤬 Actual Behavior

共有ノート投稿後、アプリを再起動するまで：
- 共有ノート投稿後は、削除が行えない。
- アイコン、アカウント名、IDの表示がされない。

### 📝 Steps to Reproduce

1. 任意のアプリで「共有する」などからAndroidの共有機能を開く。
2. Ariaを選択する。
3. 任意のアカウントを選び、共有ノートを投稿する。

### 💻 Environment

```markdown
* Model and OS of the device(s): Xperia 5 III (SIMフリー版；型番XQ-BQ42), Android 13.
* Aria: 0.7.0.
* Server URL: [m.tkngh.jp](https:m.tkngh.jp).
* Misskey: CherryPick 4.7.0.
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by poppingmoon** [comment]
ユーザー自身の情報 (`i`) の取得に失敗しているのが原因なのですが、なぜ失敗しているのか特定することはできませんでした
ただし #131 で端末に `i` をキャッシュするようにした他、サーバーからの取得時のエラーを適切に処理するようになったため最新のバージョンではこの問題は起こらなくなっています
また、#153 で `i` がない状態でもノートの削除等ができるように修正しました

**Comment by natumi-kaoru** [comment]
承知いたしました。
調査・修正ありがとうございます！

**Comment by poppingmoon** [comment]
上に挙げた対応は0.8.0に含まれています
この問題は新しいバージョンでも発生していますか？

**Comment by natumi-kaoru** [comment]
> 上に挙げた対応は0.8.0に含まれています この問題は新しいバージョンでも発生していますか？

試行したところ、この問題は発生しませんでした（使用バージョン：0.9.1）。ご対応ありがとうございます！
