### ISSUE TITLE
iOS：通知から戻ってくるとTLのテキストボックスを開けなくなる

### ISSUE THREAD

**Issue by sevenc-nanashi** [poppingmoon/aria#171]
### 💡 Summary

タイトル通りです。

### 🥰 Expected Behavior

開ける

### 🤬 Actual Behavior

開けない

### 📝 Steps to Reproduce

https://github.com/poppingmoon/aria/assets/59691627/e37098c2-fb45-4f5a-92ad-1c1b800c79b5

### 💻 Environment

```markdown
* Model and OS of the device(s): iPhone SE3 / iOS 17
* Aria: 0.9.0
* Server URL: https://voskey.icalo.net
* Misskey:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by poppingmoon** [comment]
Flutterのバージョンを上げたことによる不具合だったようです
早い段階で報告していただいて助かりました
