### ISSUE TITLE
Translation in Notifications Tab

### ISSUE THREAD

**Issue by Starcr0ss** [poppingmoon/aria#178]
### Summary

Translate the separator in the notifications tab that says "新しい通知" to "New Notifications" in English localization
![Screenshot_20240522-111240-019](https://github.com/poppingmoon/aria/assets/26168814/1ec9195f-ed47-402e-b2ca-5258b058dc6d)

### Purpose

The app is generally well-translated yet this one area has some Japanese that looks out of place in an English localization. This would make the app seem better supported for English users.

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by poppingmoon** [comment]
Thanks for pointing this out!
