### ISSUE TITLE
UI enhancements

### ISSUE THREAD

**Issue by serrq** [poppingmoon/aria#185]
• red circle: show the currently selected profile avatar, instead of the horizontal lines.

• yellow circle: might you move those buttons on the bottom?

![1000111899](https://github.com/poppingmoon/aria/assets/113377431/c3175621-77bd-4241-b016-04efdbad2171)

**Comment by poppingmoon** [comment]
You can move the tab bar (yellow circle) to the bottom with the settings ("Appearance" -> "Show timeline tab bar on bottom").

**Comment by poppingmoon** [comment]
>  Posts are very cramped. Elements are touching each other and makes it harder to differentiate between what is which part of each section, like posts contents and user info. Other elements for some reason have large margins.

You can change line heights on the "Note display" settings page to add spaces between lines.

**Comment by sneexy-boi** [comment]
> You can change line heights on the "Note display" settings page to add spaces between lines.

Tried the option, but seems to make elements larger instead...

**Comment by poppingmoon** [comment]
Making line heights larger makes other elements larger too because the sizes of some elements are defined relative to `fontSize * lineHeight`.

There are other options to change the avatar size, button size, etc. Downscaling these settings may make it better.

**Comment by sneexy-boi** [comment]
Sadly it doesn't seem to help the issue I'm having and it causes issues with other elements being to large despite missing their settings
