### ISSUE TITLE
Post editing on supported instances

### ISSUE THREAD

**Issue by sneexy-boi** [poppingmoon/aria#195]
### Summary

Allow the usage of editing posts (*Not* "Delete and edit") on support instances, such as ones running [Sharkey](https://joinsharkey.org).
[Video demonstration showing post editing.](https://github.com/poppingmoon/aria/assets/60184397/a6cac8d1-8fbd-4bbf-b88f-229987671b84)

### Purpose

This allows users running forks of Misskey (such as IceShrimp and Sharkey, which are both popular and have implemented editing) to use the proper option instead of having to delete the post which can cause inconvenience.

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by mininmobile** [comment]
i think this is the only feature that's really missing from this amazing app. when i first downloaded it i tested it out by making a post, my dumb ass immediately made a minor spelling error, but i noticed i couldn't edit it despite my instance (firefish) supporting the function
