### ISSUE TITLE
apngアイコンが再生されない

### ISSUE THREAD

**Issue by sevenc-nanashi** [poppingmoon/aria#198]
### 💡 Summary

タイトル通りです。

### 🥰 Expected Behavior

アイコンが動く

### 🤬 Actual Behavior

アイコンが動かない

### 📝 Steps to Reproduce

自分のアカウント（ https://voakey.icalo.net/@sevenc_nanashi ）はapngアイコンなので自分のユーザーページを開けば再現できます。

### 💻 Environment

```markdown
* Model and OS of the device(s): iPhone SE 3, iOS 17
* Aria: 0.9.5
* Server URL: https://voskey.icalo.net
* Misskey: 2024.3.1-voskey
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by poppingmoon** [comment]
手元のPixel 7a(Android 14)では動いています

データセーバーのアイコン画像やアニメーション画像を再生しないを有効にしていませんか？

**Comment by sevenc-nanashi** [comment]
おっと、有効でした。ごめんなさい。
