### ISSUE TITLE
Allow to remove info message `There are new notes`

### ISSUE THREAD

**Issue by foss-** [poppingmoon/aria#273]
### Summary

**Currently**

Frequently a button shows at the top obstructing the view and no way (I am aware of) to get rid of.

Guess this is rather a question than a feature request as I may be missing something (again). Had you considered opening GitHub Discussions for Aria so that users could ask questions about the client?

### Purpose

**Expected**

The button doesn't add much value. If a user follows many accounts chances are there will always be new notes. I'd rather not see that button at all and continue reading the timeline.

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by poppingmoon** [comment]
Yes, there is no option to suppress the button. I will add the option soon.

Also, I opened [Discussions](https://github.com/poppingmoon/aria/discussions). Though I am not familiar with the feature, I hope it works as a good place to communicate with users. Thanks for the suggestion.
