### ISSUE TITLE
Translate button function changes

### ISSUE THREAD

**Issue by Vezxe** [poppingmoon/aria#274]
### Summary

Rather than have the button for translate send you to a new tab, send an api request and then change the post's text directly.

As for the language the post is translated to, it can be the app's chosen interface language.

### Purpose

The app would feel much nicer if you didn't need to have a browser popup to read the translation of a post. :smiley: 

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by poppingmoon** [comment]
Does your server support `notes/translate` endpoint and the `canUseTranslator` policy is enabled for your role? If so, the app will send an api request and show the translated text as a sheet. If these conditions are not met, the fallback behavior is to open a Google Translate page with a browser.

**Comment by Vezxe** [comment]
Ah! I didn't know that was a thing, I'll look into that now, thanks
