### ISSUE TITLE
Text cursor not aligned with text

### ISSUE THREAD

**Issue by garfieldairlines** [poppingmoon/aria#302]
### 💡 Summary

I got the slightly annoying issue that the text cursor isn't aligned with the text I'm currently writing. I don't know what other info I can give to help you I don't know a lot about android software development…

![photo_2024-07-15_10-24-32](https://github.com/user-attachments/assets/bfe2052c-5cba-4738-af4b-7092ce3ea093)

### 🥰 Expected Behavior

Aligned cursor with text.

### 🤬 Actual Behavior

Not aligned cursor with text.

### 💻 Environment

```markdown
* Model and OS of the device(s): LE2123 OxygenOS 14.0
* Aria: 0.13.3
* Server URL: fedi.garfieldairlines.net
* Misskey: Sharkey v2024.5.1
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by poppingmoon** [comment]
Actually, I could not reproduce the problem and took no action for this. A possible reason why it was fixed is updating Flutter in #334.
Anyway, I am glad that your problem is fixed!
