### ISSUE TITLE
Bug: 自分のノートのリノートから編集しようとすると、そのノートではなくリノートを編集してしまう。

### ISSUE THREAD

**Issue by natumi-kaoru** [poppingmoon/aria#318]
### 💡 Summary

任意の自分のノートを _N_ 、 _N_ のリノートを _R_ とおきます。

_R_ の「…」から「編集」をタップすると、リノート付きノート（つまりリノートまたは引用）を編集する画面が開きます。これで右上または右下のボタンで編集を完了すると、 _R_ を行った者が自分であるか他人であるかで場合分けされ、それぞれ以下のようなことが起こります：

1. **_R_ が自分の行ったものである場合**
_R_ がなくなり、内容が入力した文字列である _N_ の引用が作成されます（ _R_ を編集して文字列を追加した結果、リノートが引用に変貌したものと思われます。）。
![図1](https://github.com/user-attachments/assets/594cfc83-80da-4723-85fe-b13453a498d9)
![図2](https://github.com/user-attachments/assets/b5d6c19b-19dc-4176-90a6-a62350917700)
![図3](https://github.com/user-attachments/assets/0edecc0b-a1ea-4c46-9292-7f9f650a1b93)

2. **_R_ が他人の行ったものである場合**
「No such note.」というエラーが表示され、編集が失敗します。
![図4](https://github.com/user-attachments/assets/1d1896eb-5b0d-4f52-93f2-023762c6b025)
![図5](https://github.com/user-attachments/assets/82114c2b-7197-4afb-bf6c-3c271203277e)
![図6](https://github.com/user-attachments/assets/5d83000d-21b2-4319-82c6-044de0a19cca)

推測にはなりますが、理由としては _R_ を通して _N_ を編集しようとした場合、編集対象が _N_ ではなく _R_ になるからではないでしょうか。 _R_ が他人の行ったものである場合、他人のリノートは編集できないので、エラーが起こるのではないかと考えられます。

### 🥰 Expected Behavior

リノートからであっても、自分のノートの編集を正しく行うことができる。

### 🤬 Actual Behavior

リノートからだと、自分のノートの編集ではなくそのリノートの編集を行うことになってしまう。

### 📝 Steps to Reproduce

（編集機能のあるサーバーにおいてのみ再現可能である）
1. _N_ を自分でリノートするか、または他人にリノートしてもらい、 _R_ を作成する。
2. aria上で _R_ の「…」を押し、メニューから「編集」を選ぶ。

### 💻 Environment

```markdown
* Model and OS of the device(s): Xperia 5 III, Android 13.
* Aria: 0.13.4.
* Server URL: https://m.tkngh.jp.
* Misskey: CherryPick 4.8.0.
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by poppingmoon** [comment]
ありがとうございます
