### ISSUE TITLE
タブを切り替えた際にチャンネルフラグが正常に設定されない場合がある

### ISSUE THREAD

**Issue by absol-0359** [poppingmoon/aria#329]
### 💡 Summary

タブをボタンまたはスワイプで切り替えた際、特定の1つのタブだけチャンネルフラグが正常に設定されない場合があります。

### 🥰 Expected Behavior

どのタブを開いても、表示中のタブに対応したチャンネルフラグが自動で設定される。

### 🤬 Actual Behavior

前回終了時に表示していたタブなどによって、幾つかのパターンが発生（以下、例としてソーシャル、チャンネル1、チャンネル2（以降）という風に表記）

- 初回時は、チャンネル1にしてもチャンネルフラグが付かない（チャンネル2（以降）は付く）
- 2回目以降は具体的なトリガーは不明ながら、ソーシャルタブにてチャンネルフラグが外れない場合もある
- 前回終了時にチャンネル1を表示していた場合は、起動時にチャンネル1が表示されるがチャンネルフラグ無しになり、タブを切り替えると初回時と同じ挙動になる
- タブを設定で追加などや並び替えなどを行った場合は、他のタブ（例：チャンネル2）でこの問題が発生する場合がある

### 📝 Steps to Reproduce

初回時は下記の手順で確認しました。
1. タブを幾つか追加します（例：ソーシャル、チャンネル1，チャンネル2（以降））.
2. タブをチャンネル1に切り替えます。
3. **「投稿フォーム」または「ノート」を押した際、チャンネルフラグが付いていません。**
4. チャンネル2（以降）に切り替えた後で再度操作を行うと、チャンネル2（以降）がフラグに設定されます。
5.  **その後、再度チャンネル1に切り替えると直前に表示していたチャンネルフラグのままです。**
6. そこから更にソーシャルに切り替えると、チャンネルフラグが外れます。

### 💻 Environment

```markdown
* Model and OS of the device(s):Xperia 1 V, Android 14 & Windows 11 Pro
* Aria: 0.13.7
* Server URL: misskey.backspace.fm
* Misskey: 2024.5.0-bsk-5.3.5
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by sevenc-nanashi** [comment]
自分も同じようなバグに遭遇しました。
```
* Model and OS of the device(s): iPhone SE3, iOS 18 Beta
* Aria: 0.13.7
* Server URL: voskey.icalo.net
* Misskey: 2024.5.0-voskey
```

起動時のタブ（=前回終了時のタブ）に切り替えた時にちゃんねるフラグが設定されない、という感じだと思います。
1. 任意のチャンネルを開く
2. 書き込みフォームを表示する
3. Ariaを落とす
4. Ariaを開く
5. 別のタブに行く
6. 最初のチャンネルに戻る

で再現します。

**Comment by poppingmoon** [comment]
タブを切り替える際に次のタブを前のタブと比較するはずが、最初に開いたタブと比較するようになっていたのが原因でした
お二人とも詳しく調べていただきありがとうございました
