### ISSUE TITLE
Cache custom emoji

### ISSUE THREAD

**Issue by sckemu** [poppingmoon/aria#330]
### Summary

Cache custom emoji once viewed and keep them after closing the app to use on the next view.

### Purpose

This makes it possible to reduce the amount of communication and display comfortably, especially when using from a mobile environment.

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by poppingmoon** [comment]
Aria uses [cached_network_image](https://pub.dev/packages/cached_network_image) to display emojis. This package stores images to local storage and loads them if the same image is referenced again.
The package does not support Windows and Linux, but I am not going to implement image caching for these platforms by myself.
