### ISSUE TITLE
follow-up to #306: add option to load remembered timeline position by default when opening aria

### ISSUE THREAD

**Issue by foss-** [poppingmoon/aria#363]
### Summary

https://github.com/poppingmoon/aria/issues/306 was resolved in [v0.14.0](https://github.com/poppingmoon/aria/releases/tag/v0.14.0).

Maybe I have missed a settings option, but when testing 0.14.1 aria always loads the latest post along with the banner option to jump back to the last read position in timeline.

What I would love for aria to (optionally?) do, is automatically jump to last reading position in timeline when opened.

### Purpose

This could be user error, but I don't understand if what was requested is possible already. If it is, what setting would need to be changed?

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by poppingmoon** [comment]
The option is disabled by default. It can be enabled on the tab settings page.
![](https://github.com/user-attachments/assets/758ac5b0-b52f-4661-b93a-ac64e2ac664a)

**Comment by foss-** [comment]
Awesome - sorry for the false alert then. It makes sense. I was looking for something like timeline settings, to which I was used from Pachli (tusky fork) or Fedilab. But the tabs concept makes sense. Oh and thanks again for the quick addition of allowing to remember the timeline position. This is incredibly useful and convenient.
