### ISSUE TITLE
set default “like” reaction

### ISSUE THREAD

**Issue by stellophiliac** [poppingmoon/aria#368]
### Summary

it would be nice to set what the default reaction for the like button is, rather than always being the heart. (i don’t believe this is already implemented, apologies if i missed something!)

### Purpose

this would just be a nice quality-of-life feature. also, a lot of instances have a default like reaction, and i’d personally like if i was able to set my default reaction in the app to the same one as my instance’s

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by poppingmoon** [comment]
This feature has been added in #349 and is available after v0.14.0.
You can try out the latest version from https://github.com/poppingmoon/aria/releases/v0.14.3.

**Comment by stellophiliac** [comment]
ahh, sorry for the trouble!

where could i find this in my settings? i’ve skimmed all of them and i can’t seem to find it — i’m on ios, if that makes a difference

**Comment by poppingmoon** [comment]
If you are using the TestFlight version, the feature may be available now, but the AppStore version is still in the app review process. I presume it will finish in 1 or 2 days, so please wait a while.

Once it is available, the setting appears at ”Settings for　<your account>” -> "Emoji picker" -> "Default emoji".

Also, you can check your Aria version from "Settings" -> "About Aria".

**Comment by stellophiliac** [comment]
okay, thank you!
