### ISSUE TITLE
Korean translation?

### ISSUE THREAD

**Issue by alternative00** [poppingmoon/aria#383]
### Summary

Korean translation for Aria
I want to help this!

### Purpose

for korean misskey, Aria users!

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by poppingmoon** [comment]
Thank you for the offer.

Have you already done the work?
I am going to introduce [Crowdin](https://crowdin.com/) to manage translation.
If you want to make a pull request (by editing YAML files manually), feel free to do so, but if you like to use Crowdin, please wait while I set up it for Aria.

**Comment by poppingmoon** [comment]
The setup for Crowdin was completed in #384.
You can now use it for translation at https://crowdin.com/project/aria-for-misskey.

**Comment by poppingmoon** [comment]
It seems you have translated in Crowdin.
Thank you so much!
