### ISSUE TITLE
Duplicate Account References after Login

### ISSUE THREAD

**Issue by belpolaris** [poppingmoon/aria#393]
### 💡 Summary

After installing Aria via Google Play, i authenticated with my instance. Now my account shows up twice in the sidebar and any other place where there are per-account settings like emoji.

![Screenshot_20240922-094642_Aria](https://github.com/user-attachments/assets/76d3a666-4f37-4200-aeee-50719da4bb3d)

### 🥰 Expected Behavior

A single instance of the account is displayed.

### 🤬 Actual Behavior

Two instances of the account are displayed.

### 📝 Steps to Reproduce

1. Install Aria
2. Authenticate to (Sharkey) instance
3. Receive bonus account references

### 💻 Environment

```markdown
* Model and OS of the device(s): Motorola Razr+ 2023 running Android 14
* Aria: 0.14.4
* Server URL: https://terberlo.dog
* Misskey: Sharkey 2024.8.1
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by poppingmoon** [comment]
Thanks both for the report.
I couldn't reproduce the problem by myself, but I updated the login process to remove duplicate accounts before saving them in #398, so I think this will never happen again.
If you find the problem continues, please let me know.
