### ISSUE TITLE
Aria attempts to open ANY form of file or action

### ISSUE THREAD

**Issue by Rigerhit047** [poppingmoon/aria#394]
### 💡 Summary

I will assume this is not expected, hence I will declare it as a Bug Report, since opening it in Aria just inserts the content (if possible) in a note for publishing. 

The issue is that the "AudioService" activity appears in ANY form of file. Opening an unknown file, a text file, image, you name it. 

If this is intended, I would suggest another approach, since having an app that can open any intent can lead to annoyances, since there is a new app that can open .zip files for example, users will have to confirm again their app of choice, and since it affects ALL files, you know the rest. If only Aria is capable of handling that file, then it will open it automatically without user consent, which then can lead to more frustations.

### 🥰 Expected Behavior

Since it is just for inserting on a note, I would expect only to appear on common stuff like images, videos, common text formats, and that stuff, and only through the Share dialog, not as an app capable on opening that file. 

### 🤬 Actual Behavior

![Screenshot_20241001-203957_MiXplorer](https://github.com/user-attachments/assets/cdc57d3a-83a9-49fb-bd77-82ac95c6d75b)
As seen in the screenshot above, the "AudioService" activity will always appear, that file is just a .nomedia, but it will appear for anything I try to open it, that also includes the vanilla Android app picker, but for clarification I shared that screenshot. 

### 📝 Steps to Reproduce

1. Get any file
2. Try to share it through a Share dialog, or to open it normally (if no other app can open that file) 
3. Aria will appear as one of the possible options. 

### 💻 Environment

```markdown
* Model and OS of the device(s): POCO M3,Android 14
* Aria: 0.14.4
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by poppingmoon** [comment]
This was not intended.
I just copied and pasted from the example without thinking enough.
Thanks for letting me know.
