### ISSUE TITLE
Using android "go back" freezes the app

### ISSUE THREAD

**Issue by garfieldairlines** [poppingmoon/aria#408]
### 💡 Summary

My phone has the possibility to go back to the last "window" by swiping on of the sides of the screen.
Doing so in Aria freezes it, however using the back arrow "←" or exit button "x" on media view (both top right) still let me use the app without any crashes.

### 🥰 Expected Behavior

Being able to keep using Aria when going back

### 🤬 Actual Behavior

Aria crashes, forced restart required.

### 📝 Steps to Reproduce

1. Open a post or a media
2. Swipe back
3. Aria is freezing

### 💻 Environment

```markdown
* Model and OS of the device(s): LE2123 OxygenOS 14.0
* Aria: 0.15
* Server URL: fedi.garfieldairlines.net
* Misskey: v2024.8.2 (Sharkey)
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by yuba** [comment]
最新版Ariaでも起こっています。

Aria 0.15.1  
OPP A79 5G
Android 14
