### ISSUE TITLE
sync read position between multiple devices via read marker API

### ISSUE THREAD

**Issue by foss-** [poppingmoon/aria#414]
### Summary

Not aware of a client that does this, yet I think this would be such an amazing feature. Have aria on multiple desktop and mobile devices and all clients open on the last reading position? How awesome would that be.

Brought this up with Pachli and Nik responded with some insightful questions and potential problems in https://github.com/pachli/pachli-android/issues/245#issuecomment-1807112293

### Purpose

We live in a multi device world. This would allow users to jump between devices without loosing reading position.

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by poppingmoon** [comment]
Thank you for sharing the information.
I am not familiar with Mastodon and didn't know that read marker API.

Misskey doesn't have read marker API, so this should be done with another endpoint.
However, Misskey doesn't have endpoints that do with sharing data between multiple devices.
It has the registry feature, but the data are stored per access token.

I think sharing read positions between devices is a pretty good feature, but it seems there is no way to implement this.

**Comment by foss-** [comment]
Oof - so this escalates to a misskey feature request.

**Comment by foss-** [comment]
@infirms care to elaborate on your down vote? You don't like the idea? If so why? Or you prefer a different behavior? If so why? The downvote isn't very helpful by itself.

@poppingmoon what would be a useful feature request for misskey? I am happy to file it, but if you could give me 1 or 2 keywords or approaches how this could best be solved in misskey that would be very helpful.
