### ISSUE TITLE
1.0.0 beta：プッシュ通知が有効にできない

### ISSUE THREAD

**Issue by sevenc-nanashi** [poppingmoon/aria#431]
### 💡 Summary

プッシュ通知が有効にできません。

### 🥰 Expected Behavior

プッシュ通知が有効にできる

### 🤬 Actual Behavior

```
TimeoutException after 0:00:05.000000: Future not completed
```

### 📝 Steps to Reproduce

1. プッシュ通知を有効にする

### 💻 Environment

```markdown
* Model and OS of the device(s): iPhone SE3, iOS 18
* Aria: 1.0.0 (45)
* Server URL: https://voskey.icalo.net
* Misskey: 2024.8.0-voskey
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by poppingmoon** [comment]
APNsのデバイストークンの取得に失敗しているようです
TestFlightからインストールしても同じようになりますか？

**Comment by sevenc-nanashi** [comment]
TestFlightからインストールしています。

**Comment by sevenc-nanashi** [comment]
アップデートにより一段階進むようになりましたが、テスト通知の作成で落ちています：
![image](https://github.com/user-attachments/assets/00cbbd20-88cd-4092-a59b-7717c637ecef)

**Comment by poppingmoon** [comment]
サーバーを修正しました
もう一度試していただけますか？

**Comment by sevenc-nanashi** [comment]
やってみましたが変化なしでした。

**Comment by poppingmoon** [comment]
修正しました
もう一度お願いします

**Comment by sevenc-nanashi** [comment]
動きました、ありがとうございました！
