### ISSUE TITLE
Ability to manage muted words and instances

### ISSUE THREAD

**Issue by FitikWasTaken** [poppingmoon/aria#447]
### Summary

I don't know about vanilla Misskey, but CheeryPick has a tab "Blocks and Mutes" at settings/mute-block that has the following things
![Screenshot_20241025-201956](https://github.com/user-attachments/assets/97acbd79-cf77-4eb6-8497-7a3ded06f788)

### Purpose

It helps to filter out unwanted content such as triggering topics, or just content you don't want to see and it would be useful to have something similar in-app

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by poppingmoon** [comment]
We already have this feature in Aria. Please see "Settings" -> "Settings for _your account_" -> "Mutes and Blocks".
