### ISSUE TITLE
Text Input does not have Spell Check and broken Text blocking

### ISSUE THREAD

**Issue by Linkachus17** [poppingmoon/aria#457]
### 💡 Summary

The input field does not support some useful features like: Text blocking, Spell Check…will this be added later?
Currently for Text blocking, it’s very buggy at best

### 🥰 Expected Behavior

Input field has a Spelling Check as well as ability to block a text

### 🤬 Actual Behavior

No Spell Check, Buggy Text blocking

### 📝 Steps to Reproduce

1. Assuming Spell Check is ON, Write a post with typos

### 💻 Environment

```markdown
* Model and OS of the device(s): iPhone XS iOS 18.1
* Aria: 0.15.1
* Server URL: misskey.de
* Misskey: 2024.10.1
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by poppingmoon** [comment]
It would be good to add a spell check, but I think it should be optional because things like custom emojis and MFM tags may be detected as misspellings, which can be annoying.

For text blocking, I don't understand what it means. Could you describe more about it?

**Comment by Linkachus17** [comment]
What I mean with buggy Text blocking is: When I try to drag one of the caret (or whatever it is actually called) it’s just doesn’t want to drag. I have attached a screen recording in hoping to give you better understanding of the issue


https://github.com/user-attachments/assets/6d06ec97-b6ca-4da3-b599-1999cb89f8c6

**Comment by poppingmoon** [comment]
Thank you for reporting this. 

I have implemented the spell check option in #458 and fixed the unwanted behavior of the text selection range in #459.

If you find the problem continues, please let me know.

**Comment by Linkachus17** [comment]
Sorry, but I also forgot to mention about App Push Notification. Will that be added or still planned to have App Push Notification?

**Comment by poppingmoon** [comment]
The push notifications feature was added in #406. You can try it via TestFlight.
