### ISSUE TITLE
Unable to refresh on Sharkey 2024.9.3

### ISSUE THREAD

**Issue by belpolaris** [poppingmoon/aria#474]
### 💡 Summary

#0      $checkedConvert (package:json_annotation/src/checked_helpers.dart:91)
#1      $checkedCreate.checkedConvert (package:json_annotation/src/checked_helpers.dart:28)
#2      _$$NoteImplFromJson.<anonymous closure> (package:misskey_dart/src/data/base/note.g.dart:37)
#3      $checkedCreate.<anonymous closure> (package:json_annotation/src/checked_helpers.dart:33)
#4      $checkedNew (package:json_annotation/src/checked_helpers.dart:51)
#5      $checkedCreate (package:json_annotation/src/checked_helpers.dart:30)
#6      _$$NoteImplFromJson (package:misskey_dart/src/data/base/note.g.dart:9)
#7      new _$NoteImpl.fromJson (package:misskey_dart/src/data/base/note.freezed.dart:653)
#8      _$NoteFromJson (package:misskey_dart/src/data/base/note.freezed.dart:18)
#9      new Note.fromJson (package:misskey_dart/src/data/base/note.dart:52)
#10     MisskeyNotes.homeTimeline.<anonymous closure> (package:misskey_dart/src/misskey_note.dart:60)
#11     MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#12     ListIterator.moveNext (dart:_internal/iterable.dart:354)
#13     NotesNotifier.addAll (package:aria/provider/notes_notifier_provider.dart:48)
#14     TimelineNotesNotifier._fetchNotes (package:aria/provider/api/timeline_notes_notifier_provider.dart:154)
<asynchronous suspension>
#15     TimelineNotesNotifier.build (package:aria/provider/api/timeline_notes_notifier_provider.dart:22)
<asynchronous suspension>
#16     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

The above stack trace and error occurs when i try to refresh the home timeline. At least one lost tab functions normally.

### 🥰 Expected Behavior

The home timeline is refreshed without error.

### 🤬 Actual Behavior

The home timeline does not refresh, and shows 
CheckedFromJsonException
Could not create `_$NoteImpl`.
There is a problem with "reactions".
type 'Null' is not a subtype of type 'Map<dynamic, dynamic>' in type cast

### 📝 Steps to Reproduce

Unknown steps to reproduce. Possibly react to a status?

### 💻 Environment

```markdown
* Model and OS of the device(s): Motorola Razr+ 2023
* Aria: 0.15.1
* Server URL: terberlo.dog
* Misskey: Sharkey 2024.9.3
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by poppingmoon** [comment]
It seems this commit is causing the issue.
https://activitypub.software/TransFem-org/Sharkey/-/commit/408e782507837da4c9b2164266d6f6f3e48d1642#d8ddbb6db9ccb47b0d4e1f166f57efdb87bd948b_152_171

According to the scheme of the note, the `reactions` property should always exist. So I think this should be fixed on the Sharkey side.
https://activitypub.software/TransFem-org/Sharkey/-/blob/2024.9.3/packages/backend/src/models/json-schema/note.ts?ref_type=tags#L218-226

**Comment by K4rakara** [comment]
This should be fixed in our latest release, apologies for this!

**Comment by poppingmoon** [comment]
@belpolaris @K4rakara Is this still continuing after 2024.9.4? If so, I will do some fix on our code.

**Comment by belpolaris** [comment]
I personally have not seen recurrence since the most recent updates on Sharkey and Aria. I believe this issue to be resolved.
