### ISSUE TITLE
Can't find Mastodon users

### ISSUE THREAD

**Issue by contrapunctus-1** [poppingmoon/aria#484]
I've tried following a few Mastodon users this way -
1. Open the sidebar
2. Tap Search
3. Go to the Users tab
4. Type @username@server.tld

But each time, I get "There are no users".

Aria v0.15.1 from F-Droid
LineageOS 20 (Android 13)

**Comment by poppingmoon** [comment]
I think this is not a bug from Aria because the search is done by calling the API provided by the server.

Maybe you can use the "Lookup" feature to find a remote user. (Menu -> "More!" -> "Lookup")

**Comment by contrapunctus-1** [comment]
Thanks, that worked.
