### ISSUE TITLE
iOS：写真アプリの写真を選択したい

### ISSUE THREAD

**Issue by sevenc-nanashi** [poppingmoon/aria#54]
### Summary

![IMG_0497](https://github.com/poppingmoon/aria/assets/59691627/cd6ee221-2c36-4ff6-98c2-c7111e078145)

ファイルではなく画像一覧から選択したいです。

### Purpose

基本的に画像は写真アプリで参照できる方の写真フォルダに保存されるので、それを添付するのが楽になる

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by poppingmoon** [comment]
#55 で写真アプリを開くようにしました
普段iPhoneを使っていないので報告していただきありがたいです
