### ISSUE TITLE
タブ編集画面の並び替えのハンドルが隠れる

### ISSUE THREAD

**Issue by sevenc-nanashi** [poppingmoon/aria#56]
### 💡 Summary

タイトルの通りです。

### 🥰 Expected Behavior

これくらいの余白がある
![IMG_0520](https://github.com/poppingmoon/aria/assets/59691627/3342d4ac-4cc5-4f7d-986a-6d2a3b79af07)

### 🤬 Actual Behavior

![IMG_0519](https://github.com/poppingmoon/aria/assets/59691627/c07ac4af-f8aa-41c9-9a01-49461d5ebbd9)

### 📝 Steps to Reproduce

1. タブの設定を開く

### 💻 Environment

```markdown
* Model and OS of the device(s): iOS
* Aria: 0.4.1
* Server URL: voskey.icalo.net
* Misskey: 2024.2.0-voskey
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by poppingmoon** [comment]
実はハンドル以外の部分を掴んでも並び替えできます
それはそれとしてFABで最後の要素が隠れるのは良くないので修正します
