### ISSUE TITLE
チャンネルの表示中は基本的にチャンネル内に投稿して欲しい

### ISSUE THREAD

**Issue by sevenc-nanashi** [poppingmoon/aria#68]
### Summary

https://github.com/poppingmoon/aria/assets/59691627/e06ae46a-c6ab-4f6b-b54d-d846b92cb4cf

現在、チャンネルに投稿するとチャンネルのフラグが消えてしまいます。
チャンネル表示中は基本的にチャンネル内に投稿したい場合が多いので、チャンネル表示中はデフォルトでチャンネル内に設定して欲しいです。

### Purpose

チャンネル外へ投稿するミスが減る

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by poppingmoon** [comment]
報告ありがとうございます
チャンネルへの投稿後はチャンネルをリセットしないようにするという形で修正しました
