### ISSUE TITLE
絵文字リアクションデッキ表示時に自動でキーボードを起動させるかどうかをオプションにしてほしい

### ISSUE THREAD

**Issue by natumi-kaoru** [poppingmoon/aria#84]
### Summary

標記の通りです。

### Purpose

使う頻度の高い絵文字を十分にリアクションデッキに登録している場合、出したい絵文字は決まっているのにキーボードを仕舞うためにワンタップが必要になり、少々煩雑です。

そこで、キーボードを自動で出すかどうかをオプションとして設定に追加することで、これを解決できるのではないかと思い、ご提案させていただきました。

自動でキーボードを起動させない（OFFである）場合、検索領域をタップすることでのみキーボードが起動するようになることを想定しています。
既定値はONでよいと思いますが、お任せいたします。

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by poppingmoon** [comment]
#86 で絵文字ピッカー関連の設定を新しいページに移動しました

**Comment by natumi-kaoru** [comment]
おっとそうでしたか。
探し切ることができず建ててしまい、すみません。

また設定項目の移動、ありがとうございます。これで分かりやすくなると思います。
